### ISSUE TITLE
Wiki links are broken

### ISSUE THREAD

**Issue by HiceS** [MADEAPPS/newton-dynamics#106]
Trying to access the wiki links for building because of CMAKE issues and noticed the wiki links have been broken.

**Comment by JulioJerez** [comment]
CMake was re factore and nwo work for PC, Linux and Macs

**Comment by JayFoxRox** [comment]
Issue should not have been closed - the GitHub Wiki links are still broken: The header correctly directs to Mediawiki, but none of the other links on GitHub are valid as the content wasn't migrated yet.

*(The note about CMake was unrelated and only explained why the Wiki issue was noticed)*

**Comment by JulioJerez** [comment]
well, I do not maintain the wiki,  it was a community project that started about 10 years ago, 
since them people has abandoned and move on..
