### ISSUE TITLE
dwWorldPlugins.cpp use Win32 API without fallback for other platforms

### ISSUE THREAD

**Issue by execomrt** [MADEAPPS/newton-dynamics#119]
dwWorldPluginList::LoadPlugins and UnloadPlugins should have a '#ifdef _WIN32' because it uses Win32 API. 
dgWorld constructor use LoadPlugins so the source code must be included for every platforms.

**Comment by JulioJerez** [comment]
is use
#if _MSC_VER > 1700

already,

**Comment by JulioJerez** [comment]
thsi was fixed, plugins now works on PC, Linux and Macs, in 32 and 64 bit and float or double.
