### ISSUE TITLE
dgTypes.cpp: dgFloatExceptions uses explicitly _MM_SET_FLUSH_ZERO_MODE, which is x86 instruction

### ISSUE THREAD

**Issue by execomrt** [MADEAPPS/newton-dynamics#121]
This is the fallback on non _MSC_VER, but again, I would recommend to use of official preprocessor defines __SSE2__ for enabling SSE in the whole project.

// dgTypes.h
// This will works on every platforms, including Android
#ifdef __x86_64__
#include <emmintrin.h> 
#endif

// dgTypes.cpp, in dgFloatExceptions

... 
#elif defined __SSE2__
_MM_SET_FLUSH_ZERO_MODE(...)
#endif

Other useful defines (for AVX)

__AVX512F__
__AVX2__
__AVX__
__SSE2__

**Comment by JulioJerez** [comment]
this one is ok, is only for 32 bit systems thrown  exception of some float
goes wrong, 64 system no longer allow to changer the float mask,
I think if OK to leave like the way it is because is a 32 windows only
debug for hard to find exception in release mode.
 in fact that class will be remove all together.

the engine does not use AVX,  avx code is encapsulated in a separate
plugins it onle use base SSE or SSE2

**Comment by execomrt** [comment]
I think the clearfp / controlfp is fair enough anyway. 

Speaking of SSE and SIMD, I was looking for the dgVector.h: I can contribute for the ARM neon versions, but I would like to see the file split with SSE and non SSE code before.

**Comment by JulioJerez** [comment]
do you want to split it or you want me to make.
dgVector.h that conditionally include

dgVectorScalar.inc or dgVectorSimd.inc?

them you add the third one for Arm systems?

**Comment by JulioJerez** [comment]
Actually I am going to do it anyone, I am having a hard time finding what is what.
I can have tonight.

**Comment by execomrt** [comment]
yes it should conditionally includes dgVectorScalar.h, dgVectorSimd.h (will contains SSE and I will add the Neon code). Already started to write it.

**Comment by JulioJerez** [comment]
ok the library is separated now.
I need to do some work on the scalar because the SSE4 plugin assume the simd vector, that easy to fix, I will do it next, but you can now make your dgVectorNeo.h of what ever

**Comment by JulioJerez** [comment]
alright now both scalar and simd class compile and work.

**Comment by execomrt** [comment]
Good I've almost finished the ARM Neon. I did optimisation for ARM64 as well. Needs to test before I post the file here.

**Comment by JulioJerez** [comment]
can you post in the newton forum, this way more people can get feedback on what we are doing, 
some people use newton on mobile in single thread using thread emulation and using scalar dgVector.
they will be interested on this development.

**Comment by execomrt** [comment]
I think CompProduct3 is missing in dgVectorSimd.h

**Comment by JulioJerez** [comment]
added.

**Comment by execomrt** [comment]
I've seen several things in dgTypes.h

```
#ifdef __ppc__
	#include <vecLib/veclib.h>
#endif

```
are you still supporting PowerPC Altivec ? I doubt it. You can remove that line.

```
	#ifdef __SSE4_1__
				// some linux systems still do not support dot product operations
//				#define DG_SSE4_INSTRUCTIONS_SET
				#include <smmintrin.h>
			#endif

```
Looks like a old hack, also extern "C" around the files is not necessary


```
#if defined (__ppc__) || defined (ANDROID) || defined (IOS)
	#undef DG_SSE4_INSTRUCTIONS_SET
#endif

```
Well, you can have SSE4.1 on ANDROID actually.

In general, I things SIMD should relies on something like that, more cleaner, with a single 'DR_ARCH' definited, avoiding all sort of clashes
```

#define DG_ARCH_FPU 0
#define DG_ARCH_NEON 1
#define DG_ARCH_SSE3 2
#define DG_ARCH_SSE4_1 3
#define DG_ARCH_SSE4_2 4
#define DG_ARCH_AVX 5


#if defined _M_IX86 or defined __i386__
#define DG_ARCH DG_ARCH_SSE3
#elif defined _M_X64 or defined __x86_64__
#define DG_ARCH  DG_ARCH_SSE4
#elif defined __ARM_NEON__
#define DG_ARCH  DG_ARCH_NEON
#else
#define DG_ARCH DG_ARCH_FPU
#endif

#if DG_ARCH >= DG_ARCH_NEON
#define DG_SCALAR_VECTOR_CLASS
#endif

#ifdef DG_ARCH == DG_ARCH_NEON
#include <arm_neon.h>
#elif defined DG_ARCH >= DG_ARCH_SSE3
#if defined(_MSC_VER)
#include <intrin.h>
#endif 
#include <emmintrin.h>
#endif
#endif
```

**Comment by JulioJerez** [comment]
yes the power pc stuff will go away, but the section of what simd to use, I do but think is necessary, the engine uses the lowest common denominator of the instruction set available, that allows for a simple define to select between scaler and simd.

in fact I later will go over and removed all of the special instructions.

I even which that the was not need for some, but unfortunately is does make a big difference in x86 system.

if make a file of the way you think it can be better, and I merge the best of both worlds.

**Comment by execomrt** [comment]
OK i've continued the thread on the forum. So far, SSE now works on Android, and also ARM Neon and ARM Neon 64. Will post the patch in the forum. It adds new files dgVectorSSE.h and dgVectorNEON.h (included from dgVectorSimd.h) and dgVectorArch.h (header to detects which architecture the application was compiled).
