### ISSUE TITLE
max_DOF assert with lots of objects

### ISSUE THREAD

**Issue by TrevorCash** [MADEAPPS/newton-dynamics#130]
I have synced with the latest code - I am getting a dgAssert(contact->m_maxDOF); when I spawn a lot of free objects.  I have no joints in my test scene just bodies with single collision shapes falling against a terrain.

![image](https://user-images.githubusercontent.com/2559371/46224944-fdd29a00-c314-11e8-92ad-7e9b4aeabcf9.png)

In release mode this actually results in a crash I think.

**Comment by TrevorCash** [comment]
Ok, yeah it's pretty repeat able after I spawn a few hundred objects or so

**Comment by JulioJerez** [comment]
ok I think the bug is just a typo,  and active joint is one that has both contact and is no sleeping.
this line 
			if (contact->m_contactActive || contact->m_maxDOF) {
should be like this
                       if (contact->m_contactActive && contact->m_maxDOF) {

is fix now please check again

**Comment by TrevorCash** [comment]
Ok Yeah That fixed that.  I am able to spawn alot more objects though.

How ever now I see that I am getting a different assert after I spawn quite alot (probly 1000 or so):
![image](https://user-images.githubusercontent.com/2559371/46239593-abff3380-c357-11e8-822b-d188752197eb.png)
![image](https://user-images.githubusercontent.com/2559371/46239601-b9b4b900-c357-11e8-86c2-2b67bbda3180.png)

**Comment by JulioJerez** [comment]
ok, yes that one is also a warning I added to verify that the new algorithm that build island actually run in linear time proportion to the number of bodies.  
can you set to m_rank <= 6  temporarilly only I make that change. 

I think is has been tested long enoght that we can assume that on average the number of test will be less than 6

Is good you test in debug mode, but also notice these assert are compiled out in release mode.

**Comment by TrevorCash** [comment]
Ok I'll leave that one in there as it is.

**Comment by JulioJerez** [comment]
the rank is upped by one now, keep those bugs coming, it will only make the engine stronger.
