### ISSUE TITLE
Crash in dgWorld

### ISSUE THREAD

**Issue by TrevorCash** [MADEAPPS/newton-dynamics#132]
Hi Julio - I'm not sure how it happened but I got a crash in dgWorld.  Does not happen very often for me.

![image](https://user-images.githubusercontent.com/2559371/47314072-e332ce80-d5fd-11e8-9fff-2700cf866b55.png)

**Comment by hhyyrylainen** [comment]
I also get this issue after a few minutes.

**Comment by JulioJerez** [comment]
yes I am aware of the bug, and yes is not a threatening issue, I do not
think.

It seem a joint is been created or destroyed and the code is triggered, and
it seem the latest optimization broke it.
I wouldn't no bother to fix it, I never like it anyway, I will re write it
to be more efficient and more rubust.

**Comment by hhyyrylainen** [comment]
This is a major issue in a game that I'm working on along with other people (https://github.com/Revolutionary-Games/Thrive) as it is not possible to play the game more than a few minutes without crashing. Due to that and other physics issues (physics bodies randomly jumping really high) we are considering switching to another physics engine, as this issue will block us from releasing the next version.

**Comment by JulioJerez** [comment]
fell free to switch engine if you are unsatisfied. 
I will not work under pressure of threads or an user using a different library. 
I get nothing from this.

**Comment by Untrustedlife** [comment]
Thrive is an open source game, we are getting nothing from it either.  Thanks for the response though. They werent trying to pressure you, just tell you that for us it was alot more major.

**Comment by JulioJerez** [comment]
I said I was going to fix it, but if you guys can't wait, then I can't hold you to my time schedule. 
I have to allocate the time I have  between fixing bug and adding new feature. 
so I time is what is hold ling you, the good thing is that physics libraries are a dime a dozen. 
you can change to one the fix more you requirements or that have more costumer support.

**Comment by JulioJerez** [comment]
Ok guys I believe this is now fixed.  
please sync and try again.

**Comment by hhyyrylainen** [comment]
After a little bit of testing I think this has fixed the physics crashing and glitching I was experiencing.

**Comment by TrevorCash** [comment]
Awesome!
