### ISSUE TITLE
newtondynamics.com seems to be down

### ISSUE THREAD

**Issue by svenberra** [MADEAPPS/newton-dynamics#136]
The start page only shows blank page with the word 'pageok'.
The forums give a 404 error.

**Comment by JulioJerez** [comment]
I do not understand what is going on again.

at first the side disappeared for my cell phone, now is gone everywhere, I will call go daddy to see what is wrong.

**Comment by JulioJerez** [comment]
Go Daddy is telling me that they some redirection that is happening because the site is unsecured, and maybe some malicious software got a hold to the site.

julio

**Comment by JulioJerez** [comment]
it appear the site is down because some malicious software, got a hold of it and is flooding the site with request, and somehow the site is not blacklisted, whatever that meant.

 

the say I need top may for a fire wall that secure the site.

**Comment by svenberra** [comment]
Hmm, but aren't they hosting your site?
Does GoDaddy mean that you will have to pay extra for them to protect your site?

**Comment by JulioJerez** [comment]
240 per year.

**Comment by svenberra** [comment]
Yes, now it's up again.

**Comment by svenberra** [comment]
And down it went again :(

**Comment by JulioJerez** [comment]
Yes, and this time even enter the url prevent entering.
Whoever is sowing this has a very sick mind.
They think I made money out of this.

**Comment by JulioJerez** [comment]
May we should just close the forum, and all the pay hosting and just use Google mailing list and github.

**Comment by JulioJerez** [comment]
Now even the Google search say, this site may be hacked.
This mean no want new will ever click the link anymore.

**Comment by JulioJerez** [comment]
Well they said I need to wait 2r hours, for the thing to kick in.
What I am think to do is that when is back, just delete the entire database, and see put one the tell the people the forum is close and that the can look us either in google, or within.

I read this thing called google+, google groups, google mailing list, 

I have not idea how it works, but is free and I presume the hackers will have nothing to hack there because we gave nothing to hide. And I sick and tired of these shinanigan with private hosting bs.

**Comment by svenberra** [comment]
Maybe Discord could be an alternative?
It's mainly a chat client for gamers but it seems to be picked up by coding communities as well. For example Godot Engine and Xenko. Although it's a chat it works a bit as a forum as well as it keeps all chat history. General discussion and questions is done in the chat and issues and requests can be handle on github.

**Comment by svenberra** [comment]
The site is back up.
I agree it's very strange. When GoDaddy said it was large amounts of request against the site did they mean as in a DDOS attack or that someone was trying to brute force hack into the forum?

**Comment by JulioJerez** [comment]
if they explained it went over my head,  They said that the site was been attack by malicious software so it was black listed, that I needed a firewall that so some SSN security stuff .

**Comment by svenberra** [comment]
ok, i'm no internet security guru either but i guess the site was hacked and injected with malicious code. The question is if GoDaddy helped you get rid of it or if the site is still infected?
I can see google have blacklisted your site and i dont think they remove that until you use their searchconsole tool or something like that to verify the site is safe. I clicked the link about your site being hacked on the google search page and read their guide there.

**Comment by JulioJerez** [comment]
Ah so you think some is already in the site.
I went to the the console thing, but I can't do that from work, let us do it tonight or tomorrow.

**Comment by svenberra** [comment]
Well, let's hope not. Not sure how searchconsole works exactly but it seems to have tools for detecting malware and stuff like that.

**Comment by svenberra** [comment]
seems fine now and no varning in google either

**Comment by JulioJerez** [comment]
Yes when I woke up this morning, the Google listing not longer say the red dreadfull warning that the site is hacked.
Let us let it go one more time, since I already paid for the fire wall, but if it happen again then we just switch to some free popular social service.
For now since like it was.

**Comment by JulioJerez** [comment]
I have done some research, apparently this malware spreads using guessed and / or passwords hacked from other sources then puts on a malware script with url redirect. 
 
I have reset all ftp passwords and i give you new, secure passwords:
