### ISSUE TITLE
Crashes on linux

### ISSUE THREAD

**Issue by TrevorCash** [MADEAPPS/newton-dynamics#138]
Getting runtime crashes on linux running the sandbox:

![image](https://user-images.githubusercontent.com/2559371/50497168-a1097d00-09f2-11e9-907c-058890be629e.png)

after commenting out the assert it crashes on this next error:
![image](https://user-images.githubusercontent.com/2559371/50497186-c39b9600-09f2-11e9-901c-e0e02e0db44d.png)

**Comment by JulioJerez** [comment]
The second was just a case sensitive file name.
The first one, I believe seem to be a Windows only thing that is required for mouse in imgui, I removed the assert.
Please try again.
