### ISSUE TITLE
demosSandbox cannot be run directly from visual studio without first manually copying media assets to build directory.

### ISSUE THREAD

**Issue by TrevorCash** [MADEAPPS/newton-dynamics#143]
using cmake to build vs solution:

demosSandbox cannot be run directly from visual studio without first manually copying media assets to build directory.

**Comment by DaveGravel** [comment]
I think it happen because with cmake you don't use the default build folder.

**Comment by TrevorCash** [comment]
Ah - yes that makes sense.  although It might be nice to get cmake to copy the assets in the case of isolated build folder?

**Comment by JulioJerez** [comment]
yes I notice that? how is that done?

**Comment by DaveGravel** [comment]
I never try but maybe it can help : https://stackoverflow.com/questions/13429656/how-to-copy-contents-of-a-directory-into-build-directory-after-make-with-cmake

**Comment by d3x0r** [comment]
or - just runthe install target, change where you are debugging,

**Comment by JulioJerez** [comment]
Thsi was not by design, but afte see the opration It is a desired funtionality.
so it is a feature.
