### ISSUE TITLE
Forum: Reset password does not work

### ISSUE THREAD

**Issue by Jack-mk** [MADEAPPS/newton-dynamics#147]
I can not log in to the forum anymore, so I want to reset my password, but it does not work. I get the following error message: "The e-mail/username information submitted could not be found."

**Comment by JulioJerez** [comment]
what is your user name?

**Comment by Jack-mk** [comment]
JackMK

**Comment by JulioJerez** [comment]
I send yo and email with a new password.

**Comment by Jack-mk** [comment]
Thank you, it is now resolved.
