### ISSUE TITLE
NewtonCollisionPointDistance Assert When using Doubles + Debug Mode

### ISSUE THREAD

**Issue by TrevorCash** [MADEAPPS/newton-dynamics#149]
HI Julio
I am getting an assert with some simple usage of NewtonCollisionPointDistance:

- Double Precision
- Debug Mode
- 64bit

![image](https://user-images.githubusercontent.com/2559371/53032431-0e9ebc00-342c-11e9-9575-72caf1b893b4.png)

Here is a debug-able exe:
https://drive.google.com/open?id=1AijVR4ryuFdY9fLnhemvvUEVwEOuhV4D

**Comment by JulioJerez** [comment]
was this a false alarm?

**Comment by TrevorCash** [comment]
Yes.  Was really a bug with my NewtonToUrho functions using matrices which was different in double mode.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
