### ISSUE TITLE
Demo Sandbox App start offscreen (windows)

### ISSUE THREAD

**Issue by d3x0r** [MADEAPPS/newton-dynamics#152]
How do you manage to open the display on the second monitor?  That takes some work to do :)
Every time I start it, it start on my second 800x600 monitor that is usually off (it's a projector) instead of the nice big 3740x2160 monitor that is primary.

**Comment by JulioJerez** [comment]
ah in this function DemoEntityManager::DemoEntityManager ()  
if you commnet out line 272 iy will use the default monitor.
I set it liek that because when debugging I what to have image on teh secund monity whiel I can step ove teh debugger

**Comment by d3x0r** [comment]
Ahh great thanx :) 
ya; 43inch 4k is 4x (2x2) 1920x1080 ... so it's already on a 'second monitor' for me :)
