### ISSUE TITLE
Crash in material->m_aabbOverlap

### ISSUE THREAD

**Issue by TrevorCash** [MADEAPPS/newton-dynamics#160]
This crash does not happen very often, but it did happen:

![image](https://user-images.githubusercontent.com/2559371/55907944-5e307700-5b95-11e9-8132-93c2b87939f4.png)

I never create a body without assigning userdata to it.  Not sure how rigBody0 could be null.

**Comment by JulioJerez** [comment]
did you closed this bug, was is resolved with a newer version? or is still there and you closed because it too old?

**Comment by TrevorCash** [comment]
I closed it because it was old and I cant remember. I havn't seen it in awhile
