### ISSUE TITLE
Assert in Remove Contacts

### ISSUE THREAD

**Issue by TrevorCash** [MADEAPPS/newton-dynamics#170]
I ran into an assert today:

![image](https://user-images.githubusercontent.com/2559371/59554208-aa64b280-8f5c-11e9-911d-0de2a8c4eb2a.png)

what can cause this?  it seems to happen when I attach a kinematics joints to a compound collision body

**Comment by JulioJerez** [comment]
I beleibe is harmless form before I modified the broadphase.
what happens if you ignore and continue?
if nothing happens I will removed.

**Comment by TrevorCash** [comment]
I commented it out and things run as normal.

**Comment by JulioJerez** [comment]
I believe this was fixed.
