### ISSUE TITLE
Assert dgWorldDynamicUpdate::ResolveImpulse

### ISSUE THREAD

**Issue by TrevorCash** [MADEAPPS/newton-dynamics#173]
Hi Julio,

Just Synced to latest master - I am getting the following assert when a capsule shape hits the ground:
![image](https://user-images.githubusercontent.com/2559371/61324950-d4fe9100-a7d0-11e9-95d0-f2e4dfaf7f46.png)

newton commit: 0e0fc7cbddcfb589cf3a07a268ad31e37d812980

project commit: 78476f38c9bcfbee9592df96925f3a34ef0263ae

**Comment by TrevorCash** [comment]
Things seem to work if I comment out the assert.

**Comment by JulioJerez** [comment]
sorry committed an incomplete WIP, try again.

**Comment by TrevorCash** [comment]
Ok just synced - that fixed this issue for me
