### ISSUE TITLE
Compilation error linux mint 19.2

### ISSUE THREAD

**Issue by nattydread69** [MADEAPPS/newton-dynamics#183]
with g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

newton-dynamics/sdk/dgCore/dgTypes.h:557:34: 
error: invalid conversion from ‘int’ to ‘void*’ [-fpermissive]

   return __sync_lock_test_and_set((int32_t*)ptr, value);

**Comment by harriv** [comment]
I've same problem with Ubuntu 19.04, gcc version 8.3.0 (Ubuntu 8.3.0-6ubuntu1)

**Comment by hogsy** [comment]
Looks like `__sync_lock_test_and_set` just needed to be cast to void* here, e.g.

```
return (void*)__sync_lock_test_and_set((int32_t*)ptr, value);
```

Not sure if that's all that's needed.
