### ISSUE TITLE
crash on delete dCustomJoint

### ISSUE THREAD

**Issue by TrevorCash** [MADEAPPS/newton-dynamics#187]
Im getting a crash when deleting a joint on the latest revision.  I before I delete I print ->GetBody0() to make sure the object is valid and it is.

![image](https://user-images.githubusercontent.com/2559371/65820489-0808cc00-e1e7-11e9-8f8e-37ef9564e5fd.png)

![image](https://user-images.githubusercontent.com/2559371/65820495-21117d00-e1e7-11e9-91e8-320578e072ca.png)

**Comment by JulioJerez** [comment]
I believe this was fixed. if not, you can open a new bug.
