### ISSUE TITLE
Compile failed

### ISSUE THREAD

**Issue by j4riv** [MADEAPPS/newton-dynamics#193]
"  newton-dynamics/sdk/dVehicle/dVehicleMultiBody.h:19,
                                 /newton-dynamics/sdk/dVehicle/dVehicleDifferential.cpp:13:
 newton-dynamics/sdk/dVehicle/dVehicleSolver.h:68:7: virhe: extra qualification ”dVehicleSolver::” on member ”dGaussBlockedLcp” [-fpermissive]
   68 |  void dVehicleSolver::dGaussBlockedLcp(
      |       ^~~~~~~~~~~~~~ "

https://github.com/MADEAPPS/newton-dynamics/blob/94a8b2b5a286efd0658118a98a6108a5a651e9d9/sdk/dVehicle/dVehicleSolver.h#L68

**Comment by JulioJerez** [comment]
ah yes, fixed.
Thanks
