### ISSUE TITLE
fails to compile

### ISSUE THREAD

**Issue by j4riv** [MADEAPPS/newton-dynamics#194]
"The CXX compiler identification is GNU 9.2.0"
" newton-dynamics/applications/demosSandbox/sdkDemos/toolBox/dSoundManager.cpp:279:3:  ”GetWorkingFileName” was not declared in this scope; did you mean ”dGetWorkingFileName”?
  279 |   GetWorkingFileName (fileName, path);
      |   ^~~~~~~~~~~~~~~~~~
      |   dGetWorkingFileName
make[2]: *** [applications/demosSandbox/CMakeFiles/demosSandbox.dir/build.make:752: applications/demosSandbox/CMakeFiles/demosSandbox.dir/sdkDemos/toolBox/dSoundManager.cpp.o] "

branch: newton-3.14
https://github.com/MADEAPPS/newton-dynamics/blob/d533ea459c99c6b8f5c95e764958f7e1945367ce/applications/demosSandbox/sdkDemos/toolBox/dSoundManager.cpp#L279

**Comment by JulioJerez** [comment]
no sure how you get that error the entire file is under 
#if 0
#endif
I was trying to add the sound for the vehicle demo, but I have not done yet.
Make sure you are sync to the later, in case you have a dSound that is no ifdef 0
