### ISSUE TITLE
Could you help me with the registration of the office forum?

### ISSUE THREAD

**Issue by CharlesQHappy** [MADEAPPS/newton-dynamics#201]
I‘m using this engine to do a scientfic simulation right now .  And I have registered the NewtonDynamic's forum, but haven't been actived for a long time. I really need to get help. Please...

My username is "Charles"

**Comment by JulioJerez** [comment]
I just activated you account. you can post now.

thanks for registering.

Julio

**Comment by JulioJerez** [comment]
I activated you account in the forum a few day ago.. 
No sure if you have notification.
if you haven't, let me know here.

**Comment by CharlesQHappy** [comment]
Thanks, finally!
