### ISSUE TITLE
Cannot register on the forum

### ISSUE THREAD

**Issue by hecktest** [MADEAPPS/newton-dynamics#211]
I will be using this library in my current project, and would like to participate in the forum as well.
The registration is set to admin verification instead of an e-mail verification, and nobody seems to ever check the queue. My account is stuck being inactive.

**Comment by JulioJerez** [comment]
I had to disable automatic registration because fo the porn site adding fake accounts.
what is you user name? I can activate your account.

**Comment by hecktest** [comment]
name is 'lewd' but the site is now down anyways

**Comment by JulioJerez** [comment]
ok the account is activated.
Thanks
