### ISSUE TITLE
3.14b fails to build, cannot convert void** to int*

### ISSUE THREAD

**Issue by hecktest** [MADEAPPS/newton-dynamics#217]
mingw 64
> sdk/dgCore/dgList.h:432:96: error: cannot convert ‘void**’ to ‘dgInt32* {aka int*}’ 

If anyone is getting this error, just get a later commit. Putting this out here so that it's easier to find, please keep this issue open until the next stable release.

**Comment by JulioJerez** [comment]
if you are using latest stable release 3.14b please try getting 3.14c
that and some other bugs were fixed.

**Comment by hecktest** [comment]
Okay, since there's a 3.14c now, this can be closed.
