### ISSUE TITLE
The player capsule doesn't collide with the chassis.

### ISSUE THREAD

**Issue by BenjaminGu** [MADEAPPS/newton-dynamics#246]
![image](https://user-images.githubusercontent.com/16999381/128686806-de0c6561-a060-4bcb-bf1b-32bab2f293ab.png)

The player capsule collides with tires.
However, it doesn't collide with the chassis.
Why is this happening?

**Comment by BenjaminGu** [comment]
![image](https://user-images.githubusercontent.com/16999381/128690368-9401672b-c097-4f92-a818-addb94d1dc1f.png)

And player capsule doesn't collide with a scene created by BuildCompoundScene().

**Comment by JulioJerez** [comment]
I don't know, my guess is that the chassis is a compound shape and the
player capsule post contact process code has a bug there. It should
collide, that's a bug that need fixing.

Thanks for the report.
I will debug it.

**Comment by JulioJerez** [comment]
the bug was here
```
			//if (contact->m_isIntersetionTestOnly)
			if (contactSolver.m_intersectionTestOnly)
			{
				ndBodyTriggerVolume* const trigger = body1->GetAsBodyTriggerVolume();
				if (trigger)
				{
					body1->GetAsBodyTriggerVolume()->OnTriggerExit(body0, m_timestep);
				}
				//contact->m_isIntersetionTestOnly = 0;
				contact->m_isIntersetionTestOnly = 1;
			}

```
I was testing the flag on the contact joint in order to report collision test on the same joint, when is should test the flag on the contact solver.

ok fixed. please check again 
and thanks for the report.

**Comment by JulioJerez** [comment]
It liek that you mixing thing up. I never try to see how teh player react wit teh vehicle. :)

**Comment by BenjaminGu** [comment]
It works. Thank you for your immediate help.
