### ISSUE TITLE
copy paste bug

### ISSUE THREAD

**Issue by 0xC0BA** [MADEAPPS/newton-dynamics#28]
So

newton-dynamics\coreLibrary_300\source\physics\dgCollisionBox.cpp

Line 320 

if (!((normalAlgin.m_x > dgFloat32 (0.9999f)) || (normalAlgin.m_y > dgFloat32 (0.9999f)) || (normalAlgin.m_x > dgFloat32 (0.9999f))))

**Comment by JulioJerez** [comment]
Oh wow, thanks you, fixed.
