### ISSUE TITLE
another typo bug?

### ISSUE THREAD

**Issue by 0xC0BA** [MADEAPPS/newton-dynamics#29]
\coreLibrary_300\source\newton\Newton.cpp

line 4099

return (instance->IsType(dgCollision::dgCollisionMesh_RTTI) || instance->IsType(dgCollision::dgCollisionMesh_RTTI)) ? 1 : 0;

**Comment by JulioJerez** [comment]
Oh yes that's another bug, Fix it 

 

Thank you

Julio
