### ISSUE TITLE
Roller joint limits

### ISSUE THREAD

**Issue by lperkin1** [MADEAPPS/newton-dynamics#312]
The demo for the roller joint doesn't seem to be limiting the object's movement or rotation.

I removed all the other joint examples and the spring damper.  So the object should be limited to (-1, 1).  Here's what I get.

Starting position
![image](https://github.com/MADEAPPS/newton-dynamics/assets/9002031/8fcfbc62-f682-4024-b843-4a16d1c3c0f6)

Outside limits
![image](https://github.com/MADEAPPS/newton-dynamics/assets/9002031/ae0181a2-fed0-4528-b8f8-a0b06989960a)

It's harder to see, but the rotation limits also don't lock the rotation.  Am I missing something?

**Comment by lperkin1** [comment]
Looks like I'm getting the same situation with the ndJointCylinder.

**Comment by JulioJerez** [comment]
ah my mistake, teh roller joint is very similar to the cylinder, It seemed I copy and paste the code, I do not really remember now, it was so long ago.
The cylinder seem to be correct I just tested.
and I fixed teh bug with the roller.

Please try again.

**Comment by lperkin1** [comment]
It's working.  Thanks!
