### ISSUE TITLE
Newton.h C compatibility

### ISSUE THREAD

**Issue by dxtzero** [MADEAPPS/newton-dynamics#54]
[typedef bool (*NewtonReportProgress) (...)](https://github.com/MADEAPPS/newton-dynamics/blob/master/coreLibrary_300/source/newton/Newton.h#L429)
requires inclusion of stdbool.h

in NewtonMeshVertexFormat
[NewtonMeshDoubleData m_vertex](https://github.com/MADEAPPS/newton-dynamics/blob/master/coreLibrary_300/source/newton/Newton.h#L341)
needs to be:
struct NewtonMeshDoubleData m_vertex
or
NewtonMeshVertexData m_vertex

**Comment by JulioJerez** [comment]
ha yes, fixed. 
thank you.

**Comment by dxtzero** [comment]
thanks!
