### ISSUE TITLE
SoftBody floor collision: Application crash

### ISSUE THREAD

**Issue by MarcSchoendorf** [MADEAPPS/newton-dynamics#55]
When you pick the soft body sphere in the demos sandbox and try to pull it through the ground, the application crashes.

**Comment by JulioJerez** [comment]
well it is still work in progress, the collision system is a provisional floor collision just to get the system on and running. The framework required many subsystems for it to be operational.
1-The solver.
2-The visualization.
3-Tool for generation quality mesh representation.
4-collision system 
5-adding functionality like the ability to constraint points to other bodies. 

what I do is that I work on what seem logical after I finish a new face.
Now what seem logical is to complete the solver, fallow for the collision system.
Thank for checking it out and stress testing it.
