### ISSUE TITLE
Do newton-dynamic provide constraints on rigidbody

### ISSUE THREAD

**Issue by alonecat06** [MADEAPPS/newton-dynamics#66]
I wonder whether newton-dynamic provide the constraints setting on rigidbody. So that we can set freeze the rotation round x-axis and z-axis. It is very useful when we apply the rigidbody on a character. How can I achieve this goal?

**Comment by JulioJerez** [comment]
no, newton is a physic simulator base of forces not impulse or position. changing velocity and or position is not allowed. 
the only way to do that is by making joint that constraint the motion long that directions.

**Comment by alonecat06** [comment]
Thank you for your answer.
