### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by DrLynix** [MADEAPPS/newton-dynamics#83]
Hi there, thanks for you amazing job on this physics engine.

I'm just wondering, Newton 3.13 is already two years old and master has received 1900 commits since then, I suppose a lot of things got improved/remade and such.

So what's the current state of the engine? When can we expect the next stable release?

**Comment by JulioJerez** [comment]
I am getting ready for a final release by the end of the month.

**Comment by DrLynix** [comment]
Glad to hear that!

Also, I tried to make myself an account on Newton forum, but I can't activate it since I never received the activation mail (not even in my spam folder). Is it possible that mail sending is currently broken?

**Comment by JulioJerez** [comment]
Ha yes the forum app is broken for a long time and people can't register. It needs to be updated.
if you tell me you user name I can active the account.

**Comment by DrLynix** [comment]
Sure, my username is "Lynix".

Should I use the forum to ask some questions about how to use Newton, or maybe you prefer GitHub?

**Comment by JulioJerez** [comment]
you account is active now.
you can use the forum, that way more people provide different answers and also can benefit of the discussion.

**Comment by DrLynix** [comment]
Alright, thank you!
