### ISSUE TITLE
is Networn Dynamics 100% deterministic?

### ISSUE THREAD

**Issue by Dahrkael** [MADEAPPS/newton-dynamics#84]
Hey there,
I wanted to ask this in the forum as its not really an issue but it seems registration doesnt work right now. And theres no email address to write to, so I'll ask here.

As the title suggests, I want to know if this physics library would be 100% deterministic across different hardware, to synchronize physics in a networked game to be exact.
Right now physics run on PhysX but theres some small differences that end up triggering correction and I'd like to avoid that.

Thanks

**Comment by JulioJerez** [comment]
no

**Comment by Dahrkael** [comment]
crystal clear answer!
 gracias
