### ISSUE TITLE
Registration to the forum does not work

### ISSUE THREAD

**Issue by Tymolc** [MADEAPPS/newton-dynamics#85]
Hi, I am using a ruby wrapper of newton dynamics in Sketchup (it's called MSPhysics). I wanted to ask some questions regarding your engine in the forum, but I don't seem to be able to register (I don't get an confirmation link).
Is there something you can do?

**Comment by JulioJerez** [comment]
go Daddy hosting is down, I notified them and they said will be restored with 72 ours.
They said I can fix it myself but I know nothing about web hosting so I have not choise but to wait.

Meanwhile you can post your questions about the engine here. 
Notice I am not the author of the MSPhysics plugin.

**Comment by JulioJerez** [comment]
ok the site is back on.
can you tell me you user name so that I can active your account.
There is still a problem wi th registration that has not been solved yet.

**Comment by JernejL** [comment]
@Tymolc - Email should work again now, but you will need to tell which account you registered so that we manually activate it.

**Comment by JernejL** [comment]
@Tymolc - found your username and activated it.

**Comment by Tymolc** [comment]
Oh, right. I'm sorry. Totally missed the replies. Thanks, it is working.
