### ISSUE TITLE
Assertion `info->m_allocator == this' failed.

### ISSUE THREAD

**Issue by ghost** [MADEAPPS/newton-dynamics#93]
I haven't had a chance to debug this issue yet, but was wondering if anyone else ran into it. I'm running on 64bit Arch Linux and compiling with clang in debug. Compiling with gcc results in the same issue, also running in debug.

../../libs/newton-dynamics/sdk/dgCore/dgMemory.cpp:293: virtual void *dgMemoryAllocator::Malloc(dgInt32): Assertion `info->m_allocator == this' failed.

Whether or not I set the memory system, the same assert happens when calling NewtonCreate().

**Comment by JulioJerez** [comment]
I believe this was fixed any of my Linux buidl do no show the bug.
you can re open it if you stil have it
